// Generated by gencpp from file nadie_control/ArduinoSensors.msg
// DO NOT EDIT!


#ifndef NADIE_CONTROL_MESSAGE_ARDUINOSENSORS_H
#define NADIE_CONTROL_MESSAGE_ARDUINOSENSORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace nadie_control
{
template <class ContainerAllocator>
struct ArduinoSensors_
{
  typedef ArduinoSensors_<ContainerAllocator> Type;

  ArduinoSensors_()
    : header()
    , frontLeftMm(0.0)
    , frontRightMm(0.0)
    , backLeftMm(0.0)
    , backRightMm(0.0)
    , euler_x(0.0)
    , euler_y(0.0)
    , euler_z(0.0)  {
    }
  ArduinoSensors_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , frontLeftMm(0.0)
    , frontRightMm(0.0)
    , backLeftMm(0.0)
    , backRightMm(0.0)
    , euler_x(0.0)
    , euler_y(0.0)
    , euler_z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _frontLeftMm_type;
  _frontLeftMm_type frontLeftMm;

   typedef float _frontRightMm_type;
  _frontRightMm_type frontRightMm;

   typedef float _backLeftMm_type;
  _backLeftMm_type backLeftMm;

   typedef float _backRightMm_type;
  _backRightMm_type backRightMm;

   typedef float _euler_x_type;
  _euler_x_type euler_x;

   typedef float _euler_y_type;
  _euler_y_type euler_y;

   typedef float _euler_z_type;
  _euler_z_type euler_z;





  typedef boost::shared_ptr< ::nadie_control::ArduinoSensors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nadie_control::ArduinoSensors_<ContainerAllocator> const> ConstPtr;

}; // struct ArduinoSensors_

typedef ::nadie_control::ArduinoSensors_<std::allocator<void> > ArduinoSensors;

typedef boost::shared_ptr< ::nadie_control::ArduinoSensors > ArduinoSensorsPtr;
typedef boost::shared_ptr< ::nadie_control::ArduinoSensors const> ArduinoSensorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nadie_control::ArduinoSensors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nadie_control::ArduinoSensors_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nadie_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'nadie_control': ['/home/wimble/nadie_ws/src/nadie/nadie_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nadie_control::ArduinoSensors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nadie_control::ArduinoSensors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nadie_control::ArduinoSensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nadie_control::ArduinoSensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nadie_control::ArduinoSensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nadie_control::ArduinoSensors_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nadie_control::ArduinoSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a294fb3cb90347b02e50da1332c600ef";
  }

  static const char* value(const ::nadie_control::ArduinoSensors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa294fb3cb90347b0ULL;
  static const uint64_t static_value2 = 0x2e50da1332c600efULL;
};

template<class ContainerAllocator>
struct DataType< ::nadie_control::ArduinoSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nadie_control/ArduinoSensors";
  }

  static const char* value(const ::nadie_control::ArduinoSensors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nadie_control::ArduinoSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Time of flight sensors (VL53L0X).\n\
Header  header\n\
float32 frontLeftMm\n\
float32 frontRightMm\n\
float32 backLeftMm\n\
float32 backRightMm\n\
float32 euler_x\n\
float32 euler_y\n\
float32 euler_z\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::nadie_control::ArduinoSensors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nadie_control::ArduinoSensors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.frontLeftMm);
      stream.next(m.frontRightMm);
      stream.next(m.backLeftMm);
      stream.next(m.backRightMm);
      stream.next(m.euler_x);
      stream.next(m.euler_y);
      stream.next(m.euler_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArduinoSensors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nadie_control::ArduinoSensors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nadie_control::ArduinoSensors_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "frontLeftMm: ";
    Printer<float>::stream(s, indent + "  ", v.frontLeftMm);
    s << indent << "frontRightMm: ";
    Printer<float>::stream(s, indent + "  ", v.frontRightMm);
    s << indent << "backLeftMm: ";
    Printer<float>::stream(s, indent + "  ", v.backLeftMm);
    s << indent << "backRightMm: ";
    Printer<float>::stream(s, indent + "  ", v.backRightMm);
    s << indent << "euler_x: ";
    Printer<float>::stream(s, indent + "  ", v.euler_x);
    s << indent << "euler_y: ";
    Printer<float>::stream(s, indent + "  ", v.euler_y);
    s << indent << "euler_z: ";
    Printer<float>::stream(s, indent + "  ", v.euler_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NADIE_CONTROL_MESSAGE_ARDUINOSENSORS_H
